version: '3.8'

services:
  trip-planner-nextjs:
    container_name: trip-planner-nextjs
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - /app/.next
      - /app/node_modules
    ports:
      - 3000:3000
    env_file:
      - ./.env
    networks:
      - trip-planner-postgres
  trip-planner-postgres:
    container_name: trip-planner-postgres
    image: postgres:17.5-alpine
    restart: always
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
    networks:
      - trip-planner-postgres
networks:
  trip-planner-postgres:
